version: 2

sources:
  - name: customer360_raw
    database: rahul-customer360-2026
    schema: customer360_raw
    tables:
      - name: ga4_events
      - name: crm_identity_map
      - name: crm_customers
      - name: sales_orders